(()=>{
const $=id=>document.getElementById(id);
const pillClass=s=>s==='BOOKED'||s==='PAID'?'ok':s==='CONSIDERING'?'warn':'need';
const iconFor=t=>({flight:'✈️',hotel:'🏨',stay:'🏠',car:'🚗',activity:'🎟️'})[t]||'📌';
const mapUrl=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||'');
function addStyles(){const s=document.createElement('style');s.textContent=`
.booking.live{padding:17px}.live .booking-name{font-size:12px;text-transform:uppercase;letter-spacing:.06em;font-weight:900}.live .bigrow{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;margin-top:12px}.live .airport{font-size:30px}.live .timepair{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;margin-top:10px;padding-top:10px;border-top:1px solid var(--line)}.live .timepair b{font-size:16px}.live .timepair span{font-size:11px;color:var(--muted)}.live .hotel-dates{display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:center;margin-top:12px}.live .hotel-dates b{font-size:15px}.live .hotel-dates small{font-size:10px;color:var(--muted);display:block;margin-bottom:3px}.live .nights{font-size:11px;color:var(--muted);white-space:nowrap}.live .card-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.live .mini-btn{display:inline-flex;align-items:center;gap:5px;border:1px solid var(--line);border-radius:999px;padding:7px 10px;text-decoration:none;color:var(--text);font-size:11px;font-weight:800}.event.is-past{opacity:.46}.event.is-next{background:color-mix(in srgb,var(--accent) 8%,transparent);margin:4px -6px;padding:11px 6px;border-radius:12px}.event.is-next .event-title:after{content:'  NEXT';font-size:9px;color:var(--accent);font-weight:950}.today-banner{margin:12px 0 0;padding:10px 12px;border-radius:14px;background:color-mix(in srgb,var(--accent) 9%,var(--card));font-size:12px;font-weight:850;color:var(--accent)}
`;document.head.appendChild(s)}
function renderBookings(data){const grid=$('bookingGrid');if(!grid||!data.bookings)return;grid.innerHTML=data.bookings.map(x=>{
const cls=pillClass(x.status),icon=iconFor(x.type);
if(x.type==='flight')return `<div class="card booking live route-flight"><div class="booking-top"><span class="booking-icon">${icon}</span><span class="pill ${cls}">${x.status}</span></div><div class="booking-name">${x.label}</div><div class="bigrow"><div><div class="airport">${x.from}</div><div class="booking-sub">${x.date}</div></div><div style="font-size:18px">✈️</div><div style="text-align:right"><div class="airport">${x.to}</div><div class="booking-sub">${x.nonstop?'NONSTOP':'连接待定'}</div></div></div><div class="timepair"><div><span>DEPART</span><b>${x.depart}</b></div><div>→</div><div style="text-align:right"><span>ARRIVE</span><b>${x.arrive}</b></div></div><div class="booking-sub">${x.flightNumber} · ${x.detail}</div></div>`;
if(x.type==='hotel'||x.type==='stay')return `<div class="card booking live"><div class="booking-top"><span class="booking-icon">${icon}</span><span class="pill ${cls}">${x.status}</span></div><div class="booking-name">${x.label}</div><div class="booking-main">${x.name}</div><div class="hotel-dates"><div><small>CHECK-IN</small><b>${x.checkIn}</b></div><div class="nights">${x.nights} nights</div><div style="text-align:right"><small>CHECK-OUT</small><b>${x.checkOut}</b></div></div><div class="booking-sub">${x.detail}</div>${x.address&&x.address!=='待确认'?`<div class="card-actions"><a class="mini-btn" href="${mapUrl(x.address)}" target="_blank" rel="noreferrer">📍 导航</a></div>`:''}</div>`;
return `<div class="card booking live"><div class="booking-top"><span class="booking-icon">${icon}</span><span class="pill ${cls}">${x.status}</span></div><div class="booking-name">${x.label}</div><div class="booking-main">${x.name||'待确认'}</div><div class="booking-sub">${x.detail||''}</div></div>`
}).join('')}
function updateTodayMode(){try{const now=Date.now();const events=allEvents();const next=events.find(e=>new Date(e.iso).getTime()>now);document.querySelectorAll('.event').forEach(el=>el.classList.remove('is-past','is-next'));const rows=[...document.querySelectorAll('.event')];rows.forEach((el,i)=>{const ev=events[i];if(!ev)return;const t=new Date(ev.iso).getTime();if(t<now)el.classList.add('is-past');if(next&&ev.iso===next.iso)el.classList.add('is-next')});const hero=$('today');if(hero&&!document.getElementById('todayModeBanner')){const b=document.createElement('div');b.id='todayModeBanner';b.className='today-banner';hero.appendChild(b)}const b=document.getElementById('todayModeBanner');if(b){const start=new Date('2026-12-23T08:00:00-05:00').getTime(),end=new Date('2027-01-02T21:30:00-05:00').getTime();b.textContent=now<start?'旅行前模式 · 当前显示下一项计划':now>end?'旅行已结束 · 行程保留为记录':'TODAY MODE · 已完成项目自动变灰，下一项高亮'}}catch(e){}}
async function boot(){addStyles();try{const r=await fetch('./trip-data.json?ts='+Date.now(),{cache:'no-store'});const d=await r.json();renderBookings(d)}catch(e){}updateTodayMode();setInterval(updateTodayMode,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
